" Vim5 and later versions support syntax highlighting. Uncommenting the next
" line enables syntax highlighting by default.
syntax on

" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
set background=dark

" Uncomment the following to have Vim jump to the last position when
" reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
if has("autocmd")
  filetype plugin indent on
endif

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
set showcmd		" Show (partial) command in status line.
set showmatch		" Show matching brackets.
"set ignorecase		" Do case insensitive matching
set smartcase		" Do smart case matching
set incsearch		" Incremental search
"set autowrite		" Automatically save before commands like :next and :make
"set hidden             " Hide buffers when they are abandoned
set mouse=a		" Enable mouse usage (all modes)
set hlsearch            " Search result highlight

" Normal gvim colors
highlight Normal     guifg=gray guibg=black
" Less visible comments
hi Comment ctermfg=darkgreen

" Longer command history
set history=500

" Line numbers
set number
hi LineNr cterm=bold ctermfg=darkgray

" Press F2 to help locating the cursor
hi CursorLine cterm=NONE ctermbg=blue
hi CursorColumn cterm=NONE ctermbg=blue
map <F2> :set cursorline! cursorcolumn!<CR>
set pastetoggle=<F3>

" Auto configure the buffer with modeline
set modeline
