#!/usr/bin/env python3
import sys
import urllib
import urllib.parse
if len(sys.argv[1:]) > 0:
    for arg in sys.argv[1:]:
        print(urllib.parse.quote(arg))
else:
    print(urllib.parse.quote(sys.stdin.read()))
