#!/bin/bash

clip() {
    if [ "$1" == "--help" -o "$1" == "-h" ]; then
        echo "Usage: $(basename "$0") […]" >&1
        echo "Sets clipboard content." >&1
        echo "Tiny wrapper around xclip, merely adding \`\`-selection clipboard'' argument." >&1
        echo "Calls wl-copy under Wayland." >&1
        return
    fi
    if which wl-copy >/dev/null 2>&1; then
        wl-copy "$@"
    else
        xclip -selection clipboard "$@"
    fi
}

if [ "$(basename -- "$0")" = "clip" ] || [ "$(basename -- "$0")" = "pbcopy" ]; then
    clip "$@"
fi
